---
apiVersion: v1
kind: Service
metadata:
  name: gmc-service
  namespace: tgf
spec:
  selector:
    app: gmc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gmc
  namespace: tgf
spec:
  selector:
    matchLabels:
      app: gmc
  serviceName: "gmc-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: gmc
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: gmc
        image: gemfire/gemfire-management-console:1.4.1
        ports:
        - containerPort: 8080
          name: gmc
        volumeMounts:
        - name: gmc
          mountPath: /opt/gemfire/VMware_GemFire_Management_Console
        env:
        - name: server.port
          value: "8080"
        - name: GMC_WEBSOCKET_SENDBUFFERSIZELIMIT
          value: "5120000"
        - name: PROMETHEUS_SCRAPE_INTERVAL
          value: "2s"

  volumeClaimTemplates:
  - metadata:
      name: gmc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName:
      resources:
        requests:
          storage: 4Gi
